backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: assets
collections:
  - name: element
    label: Element
    folder: element
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
