backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: assets
collections:
  - name: element
    label: Element
    folder: src/pages/element
    create: true
    fields:
      - name: title
        label: Title
      - name: order
        label: Order
        widget: number
        valueType: int
        step: 1
      - name: contentCategories
        label: Content Categories
        widget: select
        multiple: true
        options:
          - label: Metadata content
            value: Metadata content
          - label: Flow content
            value: Flow content
          - label: Sectioning content
            value: Sectioning content
          - label: Heading content
            value: Heading content
          - label: Phrasing content
            value: Phrasing content
          - label: Embedded content
            value: Embedded content
          - label: Interactive content
            value: Interactive content
          - label: Sectioning root
            value: Sectioning root
          - label: Form-associated content
            value: Form-associated content
          - label: Listed element
            value: Listed element
          - label: Submittable Element
            value: Submittable element
          - label: Resettable element
            value: Resettable element
          - label: Autocapitalize-inheriting element
            value: Autocapitalize-inheriting element
          - label: Labelable element
            value: Labelable element
          - label: Palpable content
            value: Palpable content
          - label: Script-supporting element
            value: Script-supporting element
          - label: None
            value: None
      - name: body
        label: Body
        widget: markdown
